# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(upload_to=b''),
        ),
    ]
